import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { Particles } from "@/components/magicui/particles";
import Footer from "./components/footer";
import { Toaster } from "sonner"; // 👈 Import ThemeProvider
import { ThemeProvider } from "./components/theme-provider";
import WhatsappFloatButton from "./components/whatsAppFloatButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AffareDoro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white min-h-screen flex flex-col`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="default"
          enableSystem
          disableTransitionOnChange
        >
          <div className="absolute inset-0 -z-10">
            <Particles />
          </div>
          <Toaster position="bottom-right" richColors />
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
          <WhatsappFloatButton/>
        </ThemeProvider>
      </body>
    </html>
  );
}